name: bluebubbles
title: BlueBubbles
version: 1.12.4.0
summary: BlueBubbles client for Linux
description: BlueBubbles is an open-source and cross-platform ecosystem of apps aimed to bring iMessage to Android, Windows, Linux, and more! With BlueBubbles, you'll be able to send messages, media, and much more to your friends and family.

confinement: strict
base: core22
grade: stable

plugs:
  graphics-core22:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core22

layout:
  /usr/share/libdrm:
    bind: $SNAP/graphics/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/graphics/drirc.d
  /usr/share/X11/XErrorDB:
    symlink: $SNAP/graphics/X11/XErrorDB
  /usr/share/X11/locale:
    symlink: $SNAP/graphics/X11/locale

apps:
  bluebubbles:
    command: bin/bluebubbles
    command-chain:
      - bin/graphics-core22-wrapper
    extensions:
      - gnome
    slots:
      - dbus-bluebubbles
    plugs:
      - network
      - network-manager
      - camera
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - home
      - opengl
      - audio-playback
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/samba:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/vdpau:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri

parts:
  flutter-git:
    source: https://github.com/flutter/flutter.git
    source-branch: 3.10.6
    source-depth: 1
    plugin: nil
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/bin
      mkdir -p $SNAPCRAFT_PART_INSTALL/usr/libexec
      cp -r $SNAPCRAFT_PART_SRC $SNAPCRAFT_PART_INSTALL/usr/libexec/flutter
      ln -s $SNAPCRAFT_PART_INSTALL/usr/libexec/flutter/bin/flutter $SNAPCRAFT_PART_INSTALL/usr/bin/flutter
    build-packages:
      - curl
      - clang
      - cmake
      - libgtk-3-dev
      - ninja-build
      - xz-utils
      - unzip
    override-prime: ''
    
  desktop-glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin

  bluebubbles:
    after:
      - flutter-git
      - desktop-glib-only
    source: .
    plugin: nil
    override-build: |
      set -eux
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      flutter config --no-analytics
      flutter config --enable-linux-desktop
      flutter doctor
      flutter pub get
      rm -rf build
      flutter build linux --release -v
      tmp=$(mktemp)
      chmod 644 "$tmp"
      jq '.version = "1.12.4.0"' build/linux/*/release/bundle/data/flutter_assets/version.json > "$tmp" && mv "$tmp" build/linux/*/release/bundle/data/flutter_assets/version.json
      chmod +x build/linux/*/release/bundle/bluebubbles
      cp -r build/linux/*/release/bundle/* $SNAPCRAFT_PART_INSTALL/bin/
      mv build/linux/*/release/bundle/lib/libobjectbox.so $SNAPCRAFT_PART_INSTALL/usr/lib/
    build-packages:
      - jq
      - libmpv-dev
      - libnotify-dev
    stage-packages:
      - freeglut3
      - gir1.2-appindicator3-0.1
      - libglu1-mesa
      - libmpv1
      - libnotify4
      - wmctrl
      - zenity

  graphics-core22:
    after:
      - bluebubbles
    source: https://github.com/MirServer/graphics-core22.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/graphics-core22-cleanup mesa-core22 nvidia-core22
    prime:
    - bin/graphics-core22-wrapper

  cleanup:
    after:
      - bluebubbles
    plugin: nil
    build-snaps:
      - core22
      - gtk-common-themes
    override-prime: |
      set -eux
      for snap in "core22" "gtk-common-themes"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done

slots:
  dbus-bluebubbles:
    interface: dbus
    bus: session
    name: app.bluebubbles.BlueBubbles
