name: bluebubbles
title: BlueBubbles
version: 1.12.4.0
summary: BlueBubbles client for Linux
description: BlueBubbles is an open-source and cross-platform ecosystem of apps aimed to bring iMessage to Android, Windows, Linux, and more! With BlueBubbles, you'll be able to send messages, media, and much more to your friends and family.

confinement: strict
base: core22
grade: stable

architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: arm64
    build-for: arm64

plugs:
  graphics-core22:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core22

layout:
  /usr/share/libdrm:
    bind: $SNAP/graphics/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/graphics/drirc.d
  /usr/share/X11/XErrorDB:
    symlink: $SNAP/graphics/X11/XErrorDB
  /usr/share/X11/locale:
    symlink: $SNAP/graphics/X11/locale

apps:
  bluebubbles:
    command: bin/bluebubbles
    command-chain:
      - bin/graphics-core22-wrapper
    extensions:
      - gnome
    slots:
      - dbus-bluebubbles
    plugs:
      - network
      - network-manager
      - camera
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - home
      - opengl
      - audio-playback
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/blas:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/lapack:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/samba:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/vdpau:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/dri

parts:
  desktop-glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin

  bluebubbles:
    after:
      - desktop-glib-only
    source:
      - on amd64: https://github.com/BlueBubblesApp/bluebubbles-app/releases/download/v1.12.4%2B58/bluebubbles-linux-x86_64.tar
      - on arm64: https://github.com/BlueBubblesApp/bluebubbles-app/releases/download/v1.12.4%2B58/bluebubbles-linux-aarch64.tar
    plugin: nil
    override-build: |
      set -eux
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cp -r ./* $SNAPCRAFT_PART_INSTALL/bin/
      mv lib/libobjectbox.so $SNAPCRAFT_PART_INSTALL/usr/lib/
    stage-packages:
      - freeglut3
      - gir1.2-appindicator3-0.1
      - libglu1-mesa
      - libmpv1
      - libnotify4
      - wmctrl
      - zenity

  graphics-core22:
    after:
      - bluebubbles
    source: https://github.com/MirServer/graphics-core22.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/graphics-core22-cleanup mesa-core22 nvidia-core22
    prime:
      - bin/graphics-core22-wrapper

  cleanup:
    after:
      - bluebubbles
    plugin: nil
    build-snaps:
      - core22
      - gtk-common-themes
    override-prime: |
      set -eux
      for snap in "core22" "gtk-common-themes"; do
          cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done

slots:
  dbus-bluebubbles:
    interface: dbus
    bus: session
    name: app.bluebubbles.BlueBubbles
